# Generated by Django 5.2.12 on 2026-04-05 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='escritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_captura', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_captura', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=20)),
                ('editorial', models.CharField(max_length=150)),
                ('fecha_publicacion', models.DateField()),
                ('existencia', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_captura', models.DateTimeField(auto_now=True)),
                ('escritor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.escritor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
